spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-auth
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
server:
  port: 12000



